@startuml assessment_status_flow_chart

state 編集権区分の説明 {
  案件管理:SatelliteもしくはGYROの案件管理で\nRUが操作できる状態
  査定依頼商材管理:GYROの査定依頼商材管理で\n販促が操作できる状態
}

' 「自己査定のフロー」
state 自己査定 {
  state "未査定（自己査定）" as 一時保存

[*] --> 一時保存:一時保存(RU)
一時保存:査定状況：未査定
一時保存:査定区分：自己査定
一時保存:編集権区分：案件管理

一時保存 -> 買取可能:買取可能(RU)
買取可能:査定区分：自己査定
買取可能:編集権区分：案件管理

一時保存 --> 買取不可:買取不可(RU)
買取不可:査定区分：自己査定
買取不可:編集権区分：案件管理

一時保存 --> 要預かり査定:要預かり査定(RU)
要預かり査定:査定区分：自己査定
要預かり査定:編集権区分：案件管理

' 査定やり直し
買取可能 --> 一時保存:査定をやり直す（RU）
買取不可 --> 一時保存:査定をやり直す（RU）
要預かり査定 --> 一時保存:査定をやり直す（RU）

}

' 「専門査定のフロー」
state 査定区分が専門査定 {
  state "買取可能（専門査定）" as 専門査定での買取可能
  state "買取不可（専門査定）" as 専門査定での買取不可
  state "要預かり査定（専門査定）" as 専門査定での要預かり依頼

要預かり査定 --> 未査定:預かり査定の確定（RU）
未査定:査定区分：専門査定
未査定:編集権区分：査定依頼商材管理

一時保存 --> 未査定:専門査定依頼（RU）

未査定 --> 査定中:査定を開始（販促）
査定中:査定区分：専門査定
査定中:編集権区分：査定依頼商材管理

査定中 --> 未査定:査定を辞退（販促）

査定中 --> 専門査定での買取可能:買取可能（販促）
専門査定での買取可能:査定区分：専門査定
専門査定での買取可能:編集権区分：案件管理

査定中 --> 専門査定での買取不可:買取不可（販促）
専門査定での買取不可:査定区分：専門査定
専門査定での買取不可:編集権区分：案件管理

査定中 --> 査定情報不足:査定情報不足（販促）
査定情報不足:査定区分：専門査定
査定情報不足:編集権区分：案件管理

査定情報不足 --> 査定中:査定情報入力完了（RU）

査定中 --> 専門査定での要預かり依頼:要預かり依頼（販促）
専門査定での要預かり依頼:査定区分：専門査定
専門査定での要預かり依頼:編集権区分：案件管理

専門査定での要預かり依頼 --> 未査定:預かり査定の確定（RU）

' 査定やり直し
未査定 --> 一時保存:査定をやり直す（RU: 預かり査定の場合はNG）
専門査定での買取可能 --> 一時保存:査定をやり直す（RU）
専門査定での買取不可 --> 一時保存:査定をやり直す（RU）
専門査定での要預かり依頼 --> 一時保存:査定をやり直す（RU）

}

@enduml
